# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer
import subprocess
from pathlib import Path
# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\krkr\Desktop\TERM4\cyper-security\EN_DE_criptionGui\Project Cyber\frame0")  

def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

ceaser= r"C:\Users\krkr\Desktop\TERM4\cyper-security\EN_DE_criptionGui\Project Cyber\ceaserCipher.py"  #change the path ceaser cipher verryyyy importanttttt
def ceaser1():
    window.destroy()
    subprocess.run(["python", ceaser], check=True)

rail= r"C:\Users\krkr\Desktop\TERM4\cyper-security\EN_DE_criptionGui\Project Cyber\railFence.py"  #change the path rail fence cipher verryyyy importanttttt
def rail2():
    window.destroy()
    subprocess.run(["python",rail], check=True)

rot= r"C:\Users\krkr\Desktop\TERM4\cyper-security\EN_DE_criptionGui\Project Cyber\Rot_13.py"  #change the path rot 13 cipher verryyyy importanttttt
def rot1():
    window.destroy()
    subprocess.run(["python",rot], check=True)

col= r"C:\Users\krkr\Desktop\TERM4\cyper-security\EN_DE_criptionGui\Project Cyber\columnTransposition.py"  #change the path column transposition cipher verryyyy importanttttt
def colu():
    window.destroy()
    subprocess.run(["python",col], check=True)

sub= r"C:\Users\krkr\Desktop\TERM4\cyper-security\EN_DE_criptionGui\Project Cyber\SubstitutionCipher.py"  #change the path subtutaion cipher verryyyy importanttttt
def sub1():
    window.destroy()
    subprocess.run(["python",sub], check=True)

aff= r"C:\Users\krkr\Desktop\TERM4\cyper-security\EN_DE_criptionGui\Project Cyber\affineCypher.py"  #change the path affine cipher verryyyy importanttttt
def aff1(): 
    window.destroy()
    subprocess.run(["python",aff], check=True)

window = Tk()
window.geometry("750x561")
window.configure(bg = "#000000")
 
canvas = Canvas(
    window,
    bg = "#080017",
    height = 561,
    width = 750,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)
canvas.place(x = 0, y = 0)

# Create static text
canvas.create_text(
    265.0,
    40.0,
    anchor="nw",
    text="Welcome to Cyber Project",
    fill="#FFFFFF",
    font=("Inter", 20 * -1)
)

canvas.create_text(
    240.0,
    135.0,
    anchor="nw",
    text="Please select Enc & Dec Type",
    fill="#FFFFFF",
    font=("Inter", 20 * -1)
)

# Replace images with buttons with text
button_1 = Button(
    window,
    text="Ceaser Cipher",
    bg="#2a4e78",
    fg="#ffffff",
    font=("Inter", 12),
    activebackground="#2a4e78",
    activeforeground="#ffffff",
    borderwidth=0,
    highlightthickness=0,
    command=ceaser1,
    relief="flat"
)
button_1.place(
    x=91.0,
    y=233.0,
    width=175.0,
    height=48.0
)

button_2 = Button(
    window,
    text="Rail Fence Cipher",
    bg="#2a4e78",
    fg="#ffffff",
    font=("Inter", 12),
    activebackground="#2a4e78",
    activeforeground="#ffffff",
    borderwidth=0,
    highlightthickness=0,
    command=rail2,
    relief="flat"
)
button_2.place(
    x=301.0,
    y=233.0,
    width=175.0,
    height=48.0
)

button_3 = Button(
    window,
    text="ROT 13 Cipher",
    bg="#2a4e78",
    fg="#ffffff",
    font=("Inter", 12),
    activebackground="#2a4e78",
    activeforeground="#ffffff",
    borderwidth=0,
    highlightthickness=0,
    command=rot1,
    relief="flat"
)
button_3.place(
    x=511.0,
    y=233.0,
    width=175.0,
    height=48.0
)

button_4 = Button(
    window,
    text="Column Transposition",
    bg="#2a4e78",
    fg="#ffffff",
    font=("Inter", 12),
    activebackground="#2a4e78",
    activeforeground="#ffffff",
    borderwidth=0,
    highlightthickness=0,
    command=colu,
    relief="flat"
)
button_4.place(
    x=91.0,
    y=335.0,
    width=175.0,
    height=48.0
)

button_5 = Button(
    window,
    text="Substitution Cipher",
    bg="#2a4e78",
    fg="#ffffff",
    font=("Inter", 12),
    activebackground="#2a4e78",
    activeforeground="#ffffff",
    borderwidth=0,
    highlightthickness=0,
    command=sub1,
    relief="flat"
)
button_5.place(
    x=301.0,
    y=335.0,
    width=175.0,
    height=48.0
)

button_6 = Button(
    window,
    text="Affine Cipher",
    bg="#2a4e78",
    fg="#ffffff",
    font=("Inter", 12),
    activebackground="#2a4e78",
    activeforeground="#ffffff",
    borderwidth=0,
    highlightthickness=0,
    command=aff1,
    relief="flat"
)
button_6.place(
    x=511.0,
    y=333.0,
    width=175.0,
    height=48.0
)

# Static image and text
image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    388.0,
    449.0,
    image=image_image_3
)

window.resizable(False, False)
window.mainloop()
